export function safeUrl(value) { if (!value) return ''; try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) && !url.username && !url.password ? url.href : ''; } catch { return ''; } }
const isDate = value => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value;
const hasOffset = value => typeof value === 'string' && /T\d{2}:\d{2}(:\d{2})?([+-]\d{2}:\d{2}|Z)$/.test(value) && Number.isFinite(Date.parse(value));
function expect(condition, message) { if (!condition) throw new Error(message); }
function text(value, label, allowEmpty = false) { expect(typeof value === 'string' && (allowEmpty || value.trim().length > 0), `${label} 必须是文字${allowEmpty ? '' : '且不能为空'}`); }
export function validateContent(data) {
  expect(data && typeof data === 'object', '内容必须是对象'); expect(isDate(data.updatedAt), 'updatedAt 必须是有效 YYYY-MM-DD 日期'); expect(data.contact && typeof data.contact === 'object', '缺少联系方式'); text(data.contact.wechat, '微信号', true); text(data.contact.bookingUrl, '预约链接', true); if (data.contact.bookingUrl) expect(safeUrl(data.contact.bookingUrl), '预约链接必须是 http(s) 地址'); text(data.casesNote, '案例说明');
  for (const collection of ['cases', 'articles', 'curriculum', 'courses']) expect(Array.isArray(data[collection]), `${collection} 必须是列表`);
  const ids = new Set();
  for (const [collection, items] of [['cases', data.cases], ['articles', data.articles]]) for (const item of items) { text(item.id, `${collection} 编号`); expect(!ids.has(item.id), '内容编号不能重复'); ids.add(item.id); text(item.title, '标题'); text(item.summary, '摘要'); text(item[collection === 'cases' ? 'label' : 'category'], '分类'); text(item[collection === 'cases' ? 'boundary' : 'note'], '边界说明'); if (collection === 'cases') text(item.result, '变化说明'); expect(Array.isArray(item.sections) && item.sections.length > 0, '详情需至少一个段落'); item.sections.forEach(section => { text(section.title, '段落标题'); text(section.text, '段落正文'); }); }
  data.curriculum.forEach(item => text(item, '课程主题'));
  for (const course of data.courses) { for (const field of ['id', 'title', 'audience', 'description', 'format', 'status']) text(course[field], `课程 ${field}`); expect(!ids.has(course.id), '课程编号不能重复'); ids.add(course.id); expect(['upcoming', 'open', 'closed', 'ongoing', 'ended', 'evergreen'].includes(course.status), '课程状态不支持'); for (const field of ['startAt', 'endAt', 'registrationDeadline']) { text(course[field], `课程 ${field}`, true); if (course[field]) expect(hasOffset(course[field]), `${field} 需为带时区的有效日期时间`); } if (course.status !== 'evergreen') expect(course.startAt && course.endAt, '非长期课程需开始和结束时间'); if (course.startAt && course.endAt) expect(Date.parse(course.endAt) >= Date.parse(course.startAt), '结束时间早于开始时间'); text(course.registrationUrl, '报名链接', true); if (course.registrationUrl) expect(safeUrl(course.registrationUrl), '报名链接必须是 http(s) 地址'); }
  return data;
}
export function visibleCourses(courses, now = Date.now()) {
  return courses.map(course => { const ended = course.status === 'ended' || (course.endAt && Date.parse(course.endAt) <= now); const started = course.startAt && Date.parse(course.startAt) <= now; const deadlinePassed = course.registrationDeadline && Date.parse(course.registrationDeadline) <= now; let displayStatus = ({ upcoming: '即将开放', open: '报名中', closed: '报名截止', ongoing: '进行中', ended: '已结束', evergreen: '长期可学' })[course.status]; if (!ended && course.status !== 'evergreen') { if (started && course.status !== 'closed') displayStatus = '进行中'; else if (deadlinePassed && course.status === 'open') displayStatus = '报名截止'; } return { ...course, ended, displayStatus, canRegister: !ended && !deadlinePassed && !started && ['open', 'evergreen'].includes(course.status) }; }).filter(course => !course.ended).sort((a, b) => (a.startAt ? Date.parse(a.startAt) : Infinity) - (b.startAt ? Date.parse(b.startAt) : Infinity));
}
