import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { validateContent, safeUrl, visibleCourses } from '../content-model.js';
const content = validateContent(JSON.parse(await readFile('content/site.json', 'utf8')));
const now = Date.parse('2026-10-04T12:00:00+08:00');
const course = { id: 'future', title: '示例', audience: '家长', description: '示例内容', format: '线上', status: 'open', startAt: '2026-10-10T10:00:00+08:00', endAt: '2026-10-10T11:00:00+08:00', registrationDeadline: '2026-10-09T12:00:00+08:00', registrationUrl: 'https://example.com/register' };
assert.equal(visibleCourses([course], now)[0].canRegister, true);
assert.equal(visibleCourses([{ ...course, registrationDeadline: '2026-10-03T12:00:00+08:00' }], now)[0].displayStatus, '报名截止');
assert.equal(visibleCourses([{ ...course, startAt: '2026-10-04T10:00:00+08:00', endAt: '2026-10-04T14:00:00+08:00' }], now)[0].displayStatus, '进行中');
assert.equal(visibleCourses([{ ...course, startAt: '2026-10-01T10:00:00+08:00', endAt: '2026-10-01T11:00:00+08:00' }], now).length, 0);
assert.equal(visibleCourses([{ ...course, status: 'evergreen', startAt: '', endAt: '', registrationDeadline: '' }], now)[0].canRegister, true);
assert.equal(safeUrl('javascript:alert(1)'), '');
assert.equal(safeUrl('https://user:secret@example.com'), '');
assert.throws(() => validateContent({ ...content, updatedAt: '2026-02-30' }));
assert.throws(() => validateContent({ ...content, courses: [{ ...course, startAt: '2026-10-10T10:00:00' }] }));
const html = await readFile('index.html', 'utf8');
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
assert.equal(ids.length, new Set(ids).size, 'Duplicate HTML IDs');
for (const match of html.matchAll(/href="#([^"]+)"/g)) assert.ok(ids.includes(match[1]), `Missing anchor ${match[1]}`);
for (const file of ['styles.css', 'app.js', 'assets/amy-portrait.webp', 'assets/brand-lotus.png']) await access(file);
console.log('Content, schedule transitions, safe URLs, anchor targets and assets checked.');
