import fs from 'node:fs';
let r=fs.readFileSync('src/components/Rise.astro','utf8');
const dims=[{key:'R',name:'想学',english:'READY',title:'先让心，腾出学习的空间。',text:'情绪韧性与心智成长。接住感受，理解压力与挫败，让困难可以说出来，让学习者准备好尝试。',question:'开始学习前，心里最占地方的是什么？'},{key:'I',name:'会学',english:'IMPROVE',title:'把“学好”，变成够得着的一步。',text:'锚定学习目标，练习方法与习惯。在具体行动和小成功中，逐步建立“我能做到”的经验。',question:'今天想完成哪一件自己认领的小事？'},{key:'S',name:'乐学',english:'SHINE',title:'知道自己怎么学，也知道如何调整。',text:'通过元认知与自我管理，观察过程、选择方法、检查与修正。让学习成为自己的工具。',question:'哪个方法有效？下次准备怎样调整？'},{key:'E',name:'助学',english:'ENCOURAGE',title:'让家，成为安心出发的地方。',text:'经营稳定、接纳与安全的关系，调配合适的资源。家庭支持与教育生态贯穿学习者的成长全程。',question:'我们的回应，是否让真实的困难更容易被听见？'}];
r=r.replace(/const dimensions = \[[\s\S]*?\];/,`const dimensions = ${JSON.stringify(dims)};`).replaceAll("item.key === 'E'","item.key === 'R'").replace('RISE<span class="gold-text">.</span><small>一张看见学习的地图。</small>','乐学四步<small>让学习，从心里发生。</small>').replace('看见环境、策略、动力与韧性。<br />找到适合当下的支持入口。','想学 → 会学 → 乐学。<br />助学，是贯穿全程的底座。').replaceAll('心理韧性</small>','想学</small>').replaceAll('内驱力</small>','会学</small>').replaceAll('学习策略</small>','乐学</small>').replace('成长环境<small>','助学<small>').replace('让学习发生','乐学四步').replace('情绪与鼓励 · 贯穿全程','家庭支持与教育生态 · 贯穿全程').replace(/<div class="rise-path">[\s\S]*?<\/small><\/div>/,'<a class="text-link" href="/blog/rise-four-steps/">读懂乐学四步的完整释义 ↗</a>').replace('aria-label="E 成长环境贯穿全程，R 心理韧性、I 内驱力、S 学习策略彼此支持"','aria-label="想学 R 到会学 I 到乐学 S，助学 E 贯穿全程"');fs.writeFileSync('src/components/Rise.astro',r);
for(const [collection,label,fn] of [['blog','心启花开 · 文章','publishedBlog'],['cases','实践案例','publishedCases'],['courses','课程与支持','publishedCourses']]){
 fs.writeFileSync('src/pages/'+collection+'/index.astro',`---
import Base from '../../layouts/Base.astro';
import {${fn},formatDate} from '../../lib/content';
const entries=await ${fn}();const categories=[...new Set(entries.map(e=>e.data.category))];
---
<Base title="${label}｜议敏 Amy"><section class="section page-heading"><p class="eyebrow">INTREASURE / ${label}</p><h1>${label}</h1><p>把理解带进生活，让成长有方向，也有温度。</p></section><section class="section listing">${collection==='blog'?'<div class="filters"><button class="is-active" data-filter="all" aria-pressed="true">全部</button>{categories.map(c=><button data-filter={c} aria-pressed="false">{c}</button>)}</div>':''}<div class="card-grid">{entries.map(e=><a class="card" data-category={e.data.category} href={'/${collection}/'+e.id+'/'}><p class="eyebrow">{e.data.category}</p><h2>{e.data.title}</h2><p>{e.data.description}</p><span class="card-bottom">{formatDate(e.data.publishDate)} · 阅读 ↗</span></a>)}</div>${collection==='courses'?'<p class="fine-print">目前展示课程主题，新一期日期与报名安排公布后更新。</p>':''}</section></Base>`);
 fs.writeFileSync('src/pages/'+collection+'/[id].astro',`---
import {render} from 'astro:content';
import Base from '../../layouts/Base.astro';
import Contact from '../../components/Contact.astro';
import {${fn},formatDate} from '../../lib/content';
export async function getStaticPaths(){return (await ${fn}()).map(entry=>({params:{id:entry.id},props:{entry}}));}
const {entry}=Astro.props; const {Content,headings}=await render(entry);
---
<Base title={entry.data.title+'｜议敏 Amy'} description={entry.data.description} type="article"><article class="article-shell"><header class="article-header"><a class="text-link" href="/${collection}/">← ${label}</a><p class="eyebrow">{entry.data.category}</p><h1>{entry.data.title}</h1><p class="article-description">{entry.data.description}</p><p class="article-meta">议敏 Amy · 网站发布 {formatDate(entry.data.publishDate)}</p></header><div class="article-grid"><aside><p class="eyebrow">本文目录</p>{headings.filter(h=>h.depth===2).map(h=><a href={'#'+h.slug}>{h.text}</a>)}</aside><div class="prose"><Content />${collection==='blog'?'{entry.data.note&&<p class="source-note">{entry.data.note}</p>}{entry.data.wechatUrl&&<a class="button button-green" href={entry.data.wechatUrl} target="_blank" rel="noopener noreferrer">阅读公众号来源原文 ↗</a>}':collection==='cases'?'<div class="observation"><h3>{entry.data.result}</h3><p>{entry.data.boundary}</p></div><p class="source-note">案例经脱敏整理，省略姓名、学校等可识别信息。</p>':'<div class="observation"><p>适合：{entry.data.audience}</p><p>{entry.data.format}</p></div>'}<hr /><a class="text-link" href="/${collection}/">继续阅读 ↗</a></div></div></article><Contact /></Base>`);
}
fs.writeFileSync('src/pages/rss.xml.ts',`import rss from '@astrojs/rss';import {publishedBlog} from '../lib/content';export async function GET(context:any){return rss({title:'心启花开 · 议敏 Amy',description:'学习赋能、家庭关系与成长记录',site:context.site,items:(await publishedBlog()).map(e=>({title:e.data.title,description:e.data.description,pubDate:e.data.publishDate,link:'/blog/'+e.id+'/'})),customData:'<language>zh-cn</language>'});}`);
fs.writeFileSync('public/robots.txt','User-agent: *\nAllow: /\nSitemap: https://amyxie.yiloo.cn/sitemap-index.xml\n');
const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version='2.0.0';pkg.scripts={dev:'astro dev',build:'astro build',check:'astro check',preview:'astro preview',deploy:'wrangler pages deploy dist --project-name=amy-site'};pkg.engines={node:'>=24'};pkg.packageManager='pnpm@11.25.0';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');
